### ISSUE TITLE
Repository Move!

### ISSUE THREAD

**Issue by Flydiverny** [external-secrets/kubernetes-external-secrets#554]
Kubernetes External Secrets has moved to a new home in the external-secrets organization.

This might cause a few issues for you!

- The old repository URL of `https://godaddy.github.io/kubernetes-external-secrets/index.yaml` will no longer work!
Please change your repository to point to `https://external-secrets.github.io/kubernetes-external-secrets/index.yaml`
```sh
helm repo remove external-secrets
helm repo add external-secrets https://external-secrets.github.io/kubernetes-external-secrets/
```

Will try to update this issue with relevant changes :)
I'm guessing the image repository will change as well and there will be a new release out in connection to that :)

**Comment by jonatasbaldin** [comment]
If anything else changes because of the move, let's please document here. I'll link this issue in the README header, so people can easily find it.

**Comment by jonatasbaldin** [comment]
You can also ask any questions on the #external-secrets channel on the Kubernetes Slack.

**Comment by jonatasbaldin** [comment]
## What is happening? 🤔
Multiple people/companies are joining efforts to create a standard way to manage External Secrets within Kubernetes and one of our first steps was to move the repository to a vendor neutral organization.

We are bootstrapping a new project written in Golang, based on [this](https://github.com/itscontained/secret-manager
) and [this](https://github.com/ContainerSolutions/externalsecret-operator) project, since that's the major language of choice in the Kubernetes space.

Once the new solution is ready, tested and stable, we will replace this current project, with the proper deprecation warnings and migration instructions.

This project will keep receiving normal updates from its community and maintainers.

If you want to participate in this exciting new organization, please reach out in the #external-secrets channel on the [Kubernetes Slack](https://slack.k8s.io/).

**Comment by eitanas1** [comment]
Looks like both repositories (godaddy and github) is inaccessible now. Do I miss something?

**Comment by hayao-k** [comment]
It seems that the old URL is still listed on Artifact HUB.
Sorry if I shouldn't have written here.
https://artifacthub.io/packages/helm/external-secrets/kubernetes-external-secrets

**Comment by shay-berman** [comment]
Hi, few questions please:

1. Any estimation when the new project will be ready?
2. Does the migration plan for the new project going to be disruptive for the pods?
3. If we need to use external secret for our k8s application, is it the right path to use this project kubernetes-external-secrets and later on to migrate? or its better to use alternative and return back once the new project is stable?

**Comment by jonatasbaldin** [comment]
Hi @shay-berman!

1. We are having by-weekly meetings to discuss what we are doing, but we have no estimation yet. You can find the project [here](https://github.com/external-secrets/external-secrets).
2. It will probably be disruptive on the controller side since we are working on a new CRD spec. We will try to make it _not disruptive_ on the Pods using the generated secrets though, but it's too early to be 100% confident there.
3. We suggest to use one of the following three projects for now and migrating to the new solution once it's stable (we will let everyone now):
- https://github.com/external-secrets/kubernetes-external-secrets
- https://github.com/ContainerSolutions/externalsecret-operator
- https://github.com/itscontained/secret-manager

Hope this answers all of your questions!

Cheers,

**Comment by Geethree** [comment]
Mildly curious if it was ever discussed getting this into the k8s sigs? 

https://github.com/kubernetes-sigs

**Comment by Flydiverny** [comment]
## KES 6.1.0 has been released using the new container registry on github!
https://github.com/orgs/external-secrets/packages/container/package/kubernetes-external-secrets

## [6.1.0](https://github.com/external-secrets/kubernetes-external-secrets/compare/6.0.0...6.1.0) (2020-12-22)


### Features

* add general support for isBinary for all backends ([#585](https://github.com/external-secrets/kubernetes-external-secrets/issues/585)) ([e138a28](https://github.com/external-secrets/kubernetes-external-secrets/commit/e138a28973aeadb9902195ca889147a2705f43e4))
* restart watcher if no events seen for specified period (default 60 sec) ([#532](https://github.com/external-secrets/kubernetes-external-secrets/issues/532)) ([bb1ed9e](https://github.com/external-secrets/kubernetes-external-secrets/commit/bb1ed9eefde360d55f25cdd4767440f0f9f35cde))
* **helm:** add the ability to set the priorityClassName ([#534](https://github.com/external-secrets/kubernetes-external-secrets/issues/534)) ([e719c87](https://github.com/external-secrets/kubernetes-external-secrets/commit/e719c8724f4496d51f962b689b40ee49a0cd928a))
* **metrics:** add metrics names following Prometheus best practices, **deprecating** old metrics names! ([#540](https://github.com/external-secrets/kubernetes-external-secrets/issues/540)) ([5b5a00f](https://github.com/external-secrets/kubernetes-external-secrets/commit/5b5a00fdad1100abf057c2d944643469174d2048))


### Bug Fixes

* **values:** imagePullSecrets was wrongly indented under image ([#577](https://github.com/external-secrets/kubernetes-external-secrets/issues/577)) ([7861473](https://github.com/external-secrets/kubernetes-external-secrets/commit/78614739a7e8de9aab85ce5e063b5bde8f6c0a2b)), closes [#522](https://github.com/external-secrets/kubernetes-external-secrets/issues/522)
* configure nestedKey in logger to avoid invalid json ([#568](https://github.com/external-secrets/kubernetes-external-secrets/issues/568)) ([a430320](https://github.com/external-secrets/kubernetes-external-secrets/commit/a430320e8b9857154b4eca888fa5775ba3e1cda5))
* **deps:** bumping @grpc/grpc-js to 1.1.8 ([#550](https://github.com/external-secrets/kubernetes-external-secrets/issues/550)) ([4e88026](https://github.com/external-secrets/kubernetes-external-secrets/commit/4e88026fb21b73f2242226548abad80479d33a46))
* **deps:** bumping lodash from 4.17.19 to 4.17.20 ([#545](https://github.com/external-secrets/kubernetes-external-secrets/issues/545)) ([6c9d60d](https://github.com/external-secrets/kubernetes-external-secrets/commit/6c9d60d426405e16bce7ee00b542dde43b5e7171))

**Comment by jonatasbaldin** [comment]
@Geethree yeah, we discussed it! It's a long road to get there, but we will totes try for it :)

**Comment by Geethree** [comment]
Gotcha. I’m curious if/how the community could help with that process?

**Comment by jonatasbaldin** [comment]
We still don't know how @Geethree 😅 Our first priority is to get the code base to a stable state, then we will discuss the steps to get into a SIG or something like it!

If you wanna help around, please join us on the Kubernetes Slack :)

**Comment by yitsushi** [comment]
> Once the new solution is ready, tested and stable, we will replace this current project, with the proper deprecation warnings and migration instructions.

Is there any migration documentation somewhere? Where can I find it if it exists, I tried to find, but I couldn't land on success.
