### ISSUE TITLE
Im getting error on openshift 4.7

### ISSUE THREAD

**Issue by chechuironman** [external-secrets/kubernetes-external-secrets#832]
Im getting this error

status:
  lastSync: '2021-09-14T19:48:16.695Z'
  observedGeneration: 1
  status: 'ERROR, no matching operation was found'

any idea?

**Comment by nhenderson** [comment]
@chechuironman I just installed the `external-secrets` helm chart on OpenShift 4.7. So, I can confirm the chart does indeed work on 4.7. 

At first it wasn't syncing because I didn't hand the chart the following environment variables:
```
AWS_REGION
AWS_DEFAULT_REGION
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```
So, I uninstalled the chart and re-installed with the above environment variables and it started syncing for me.
I do not remember seeing an "no matching operation was found" error, though.

**Comment by chechuironman** [comment]
I'm trying it on IBM Cloud :(
